name: Publish on Deno Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno run -A https://deno.land/x/lume@v1.5.1/ci.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: lume
          entrypoint: serve.ts
